FROM node:20.15.0 as build

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .


# Set build-time environment variable
ARG REACT_APP_BE_URL
ENV REACT_APP_BE_URL=$REACT_APP_BE_URL


RUN yarn build

# Production Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
