version: "3.9"

services:
  backend:
    image: ubudab109/myproject-backend:latest
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - db
    expose:
      - "9000"  # PHP-FPM internal
    # volumes:
    #   - ./backend:/var/www/backend

  frontend:
    image: ubudab109/myproject-frontend:latest
    container_name: frontend
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"  # host aman, port 80 VPS bebas
    volumes:
      - ./docker/nginx/prod-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: myweb123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
