services:
  backend:
    image: ubudab109/myproject-backend:latest
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-network
    ports:
      - "9000:9000"   # BUKA backend ke host VPS

  frontend:
    image: ubudab109/myproject-frontend:latest
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    ports:
      - "3008:80"   # BUKA frontend ke host VPS

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: myweb123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
