services:
  backend:
    image: ubudab109/myproject-backend:latest
    container_name: backend
    env_file:
      - ./backend/.env
    depends_on:
      - db

  nginx-backend:
    image: nginx:alpine
    container_name: nginx-backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  frontend:
    image: ubudab109/myproject-frontend:latest
    container_name: frontend
    ports:
      - "80:80"

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: myweb123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
