version: "3.9"

services:
  backend:
    image: ubudab109/myproject-backend:latest
    container_name: backend
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    networks:
      app-network:
        aliases:
          - backend
    ports:
      - "9000:9000"

  backend-nginx:
    image: nginx:alpine
    container_name: backend-nginx
    depends_on:
      - backend
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/prod-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9001:80"
    networks:
      - app-network

  frontend:
    image: ubudab109/myproject-frontend:latest
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3008:80"     # internal port untuk VPS Nginx
    env_file:
      - ./frontend/.env.production
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: myweb123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
