name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ubudab109/myproject-backend:latest
        env:
          COMPOSER_ALLOW_SUPERUSER: 1
          COMPOSER_MEMORY_LIMIT: -1


      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: ubudab109/myproject-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            mkdir -p ~/apps/myproject
            cd ~/apps/myproject
            
            # Hanya pull image CI/CD, jangan clone git lagi
            docker-compose pull
            docker-compose up -d

            # Jalankan Makefile commands
            docker-compose exec backend php artisan key:generate
            docker-compose exec backend php artisan storage:link
            docker-compose exec backend php artisan migrate
            docker-compose exec backend php artisan db:seed
